from chameleon.config_gen import render_config
from chameleon.profile import Profile


def _profile(**overrides) -> Profile:
    base = {
        "name": "p",
        "theme": None,
        "skinparams": {},
        "handwritten": False,
    }
    base.update(overrides)
    return Profile(**base)


def test_minimal_profile_emits_only_header() -> None:
    out = render_config(_profile(name="default"))
    assert out == "' generated by chameleon from profile: default\n"


def test_header_uses_profile_name() -> None:
    out = render_config(_profile(name="whiteboard"))
    assert out.splitlines()[0] == "' generated by chameleon from profile: whiteboard"


def test_handwritten_true_emits_option_directive() -> None:
    out = render_config(_profile(handwritten=True))
    assert "!option handwritten true" in out.splitlines()


def test_handwritten_false_omits_option_directive() -> None:
    out = render_config(_profile(handwritten=False))
    assert not any("handwritten" in line for line in out.splitlines())


def test_skinparam_bool_lowercased() -> None:
    out = render_config(_profile(skinparams={"shadowing": False, "monochrome": True}))
    lines = out.splitlines()
    assert "skinparam shadowing false" in lines
    assert "skinparam monochrome true" in lines


def test_skinparam_numbers_and_strings_pass_through() -> None:
    skinparams = {
        "defaultFontSize": 14,
        "padding": 1.5,
        "defaultFontName": "Comic Sans MS",
    }
    out = render_config(_profile(skinparams=skinparams))
    lines = out.splitlines()
    assert "skinparam defaultFontSize 14" in lines
    assert "skinparam padding 1.5" in lines
    assert "skinparam defaultFontName Comic Sans MS" in lines


def test_theme_is_not_emitted_in_config() -> None:
    out = render_config(_profile(theme="sketchy"))
    assert "sketchy" not in out
    assert "theme" not in out.lower()


def test_combined_profile_full_output() -> None:
    profile = _profile(
        name="whiteboard",
        theme="sketchy",
        skinparams={"shadowing": False, "defaultFontName": "Comic Sans MS"},
        handwritten=True,
    )
    lines = render_config(profile).splitlines()
    assert lines[0] == "' generated by chameleon from profile: whiteboard"
    assert "!option handwritten true" in lines
    assert "skinparam shadowing false" in lines
    assert "skinparam defaultFontName Comic Sans MS" in lines


def test_skinparam_insertion_order_preserved() -> None:
    profile = _profile(skinparams={"alpha": 1, "beta": 2, "gamma": 3})
    skinparam_lines = [
        line for line in render_config(profile).splitlines() if line.startswith("skinparam ")
    ]
    assert skinparam_lines == [
        "skinparam alpha 1",
        "skinparam beta 2",
        "skinparam gamma 3",
    ]


def test_output_ends_with_newline() -> None:
    out = render_config(_profile(skinparams={"shadowing": True}))
    assert out.endswith("\n")
