"""Profile -> plantuml config file."""

from __future__ import annotations

from typing import Any

from chameleon.profile import Profile


def render_config(profile: Profile) -> str:
    lines: list[str] = [f"' generated by chameleon from profile: {profile.name}"]

    if profile.handwritten:
        lines.append("!option handwritten true")

    for key, value in profile.skinparams.items():
        lines.append(f"skinparam {key} {_format_value(value)}")

    return "\n".join(lines) + "\n"


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)
