' Blob ID: 07c86b6f090639ed83c436120a0802d80e7a7164
' Original Path: /packages/utu-web-components/src/components/RecordVideo/sequence.puml
' Source: World of Code

@startuml
RecordVideo -> ReadableStorage **: create
RecordVideo -> ReactMediaRecorder **: create (with storage)
RecordVideo -> tus_uploader **: create (with reader)
loop
    RecordVideo -> ReactMediaRecorder: start
    loop until stopped
        tus_uploader -> ReadableStorage: read()
    end
    RecordVideo -> ReactMediaRecorder: stop
    RecordVideo -> FeedbackAPI: sendFeedback()
    RecordVideo -> ReadableStorage !!: GC
    RecordVideo -> ReadableStorageN **: create
    RecordVideo -> ReactMediaRecorder !!: GC
    RecordVideo -> ReactMediaRecorderN **: create (with storage)
    RecordVideo -> tus_uploader !!: GC
    RecordVideo -> tus_uploaderN **: create (with reader)
end
@enduml
