' Blob ID: 090915807e02bf364c42eb6f85827f29f6ea3f48
' Original Path: /docs/gradivo/plantuml/DPU.puml
' Source: World of Code

@startuml


skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam Linetype polyline
skinparam actorStyle awesome

left to right direction


actor "Neprijavljen uporabnik" AS AU
actor "Uporabnik" AS U
actor "Predstavnik občine" AS PO
actor "Moderator" AS MO
actor "Administrator" AS AD

actor "Google maps" AS GM 

actor "Partnerski zunanji sistem" AS PZS

rectangle "Občinski obveščevalnik" {
  
  'ADMIN'
  usecase "Dodajanje moderatorja" AS DM
  usecase "Odstranitev moderatorja" AS OM
  'MODERATOR'
  usecase "Urejanje predloga" AS UP
  usecase "Brisanje predloga" AS BP
  usecase "Omogočanje / onemogočanje uporabnika" AS OU2
  'PREDSTAVNIK OBCINE'
  usecase "Priprava statističnih podatkov" AS PSP
  usecase "Dodajanje novic" AS DN
  usecase "Arhiviranje predlogov" AS AP
  'UPORABNIK' 
  usecase "Dodajanje predloga s sliko in lokacijo" AS DP
  usecase "Komentiranje predloga" AS KP
  usecase "Všečkanje / nevšečkanje predloga" AS VP
  'usecase "Dodajanje slike" AS DS
  'usecase "Dodajanje lokacije" AS DL
  usecase "Ocenjevanje arhiviranega predloga" AS OAP
  'ANONIMNI UPORABNIK'
  usecase "Registracija" AS R
  usecase "Prijava" AS P
  usecase "Odjava" AS O
  usecase "Iskanje predlogov" AS PP
  usecase "Filtriranje predlogov" AS SP
  usecase "Pregled arhiviranih predlogov" AS PAP
  
  note "API" AS blank
  
}

DP .down----> GM:include
BP .up->UP:extend

SP .up-> PP:extend
SP .up->PAP:extend

PSP -down-->blank
blank -down--> PZS

AD -> MO
MO -> PO
PO -> U
U -> AU

AD -down--> DM
AD -down--> OM

MO -down--> UP
MO -down--> OU2

PO -down--> PSP
PO -down--> DN
PO -down--> AP

U -down--> DP
U -down--> KP
U -down--> VP
U -down--> OAP
U -down--> O

AU -down--> P
AU -down--> R
AU -down--> PP
AU -down--> PAP

@enduml
