' Blob ID: 11c3e6880aaa23f682a02b668a32e624e9dd47db
' Original Path: /teoz-duration.plantuml
' Source: World of Code

@startuml
!pragma teoz true

{start} Alice -> Bob : start doing things during duration
Bob -> Max : something
Max -> Bob : something else
{end} Bob -> Alice : finish
{start} <-> {end} : duration


@enduml
