' Blob ID: 12f1d1a12f5386ceb20bcb5da0ea86c283e21534
' Original Path: /GameLoopActivityDiagram.puml
' Source: World of Code

@startuml
start
:Get time from CADisplayLink;
:Call level.moveBall(time);
if (Level has ball?) then (yes)
    :Update ballView center;
else (no)
if (Ball exited level?) then (yes)
    :ballView = nil;
else (no)
endif
endif
if (Ball collides with peg?) then (yes)
    :Light up collided pegView;
else (no)
endif
if (Can remove lit pegs?) then (yes)
    :Fade out lit pegViews one by one;
else (no)
endif
stop
@enduml
