' Blob ID: 195494b722cf0d851fbf236d57a0c64b3d5537f2
' Original Path: /schedule1.plantuml
' Source: World of Code

@startuml
robust "Web Browser" as WB
concise "Web User" as WU
@WB
0 is idle
+200 is Proc.
+100 is Waiting
@WU
0 is Waiting
+500 is ok
@enduml
