' Blob ID: 1a508c1c21602645cea253ff18ca009d3397a10a
' Original Path: /src/plantuml/use_case/sample/actor.pu
' Source: World of Code

@startuml

:First Actor23:
:Another\nactor: as Men2
actor Men3
actor :Last actor: as Men4

@enduml
