' Blob ID: 1e1803791192cabfb054e50dce98fba3aa8236c8
' Original Path: /src/main/java/csheets/worklog/n1140807/sprint4/lang05_03_designDC.puml
' Source: World of Code

@startuml

class  MacroWindowController {
-uiController
+newMacro(String name, String instructions)
+createMacro(MacroWorkbookRepo mWorkbookRepo, String name, String instructions)
+validateMacroName(String macroName)
+runMacro(String instructions, String name)
+getMacro(String macroName)
+listAvailableMacros()
}


class MacroWorkbookRepo{
-macros
+addMacro(Macro macro)
+getMacro(String macroName)
+ values()
+listAvailableMacros()
}

class MacrosExtension{
+getUIExtension(UIController uiController)
+extend(Spreadsheet spreadsheet)
}

class MacroWindowUI{
-ctrlMacro
-updateMacroList()
}

class Macro{
-name
-sheet
-lines
-formulas
-parameters
-repo
+validateName(String name)
+getName()
+getMacroText()
+addLine(String line)
+run()
+convertToFormulas(List<String> lines)
+macroReplace()
+addAllAtFirst(List<String> destination, List<String> source, int currentLine)
+getParameters(String macroDeclaration)
+evaluate()
+accept(ExpressionVisitor visitor)
+equals(Object o)
+hashCode()
}

abstract SpreadsheetExtension{
-delegate
-name
+SpreadsheetExtension(Spreadsheet delegate, String name)
+getExtension(String name)
}

MacroWorkbookRepo --|> SpreadsheetExtension
MacrosExtension --> MacroWorkbookRepo
MacroWindowUI --> MacroWindowController
MacroWindowController --> MacroWorkbookRepo
MacroWindowController --> Macro

@enduml
