' Blob ID: 21bd6c3dab8b7e71e33e8ca715f5cdcce6f6e2b5
' Original Path: /MyLearning/deadLock_timing.uml
' Source: World of Code

@startuml

robust "Condition1" as WB
concise "用户1" as WU
concise "用户2" as WU_2

@0
WU is 空闲
WB is Initial

@100
WU -> WB : URL
WU is 等待中
WB is Locked

@300
WB is 等待中
@enduml
