' Blob ID: 22a6449fdaaf782a5e99088dced9406b43ef064b
' Original Path: /uml/class-diagram.wsd
' Source: World of Code

@startuml

entity Category

Category : string name
Category : string description
Category : boolean is_active
Category : date created_at

Category : create()
Category : update()
Category : activate()
Category : deactivate()
Category : delete()


abstract Entity 

Entity : UniqueEntityId uniqueEntityId
Entity : string id

Entity : toJSON()

Entity <|-- Category
@enduml

