' Blob ID: 24d83419b0d1e893954ecb4b162fd7ee52c258e1
' Original Path: /article/img/article.pu
' Source: World of Code

@startuml

hide empty members

class "Module A" as A

class "Module B" as B

A --> B : dependency
A --> B : flow of control

@enduml
