' Blob ID: 24f0b22e7965c4216334da75f8aa7b22cfa4528c
' Original Path: /documentation/uml/behavior-diagrams/timing-diagram/frontend.puml
' Source: World of Code

' http://plantuml.com/timing-diagram

@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting


robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU -> WB : URL
WU is Waiting
WB is Processing

@300
WB is Waiting

@enduml
