' Blob ID: 2806cdfe34ec6aa0f8ddf46800983c5f311fd5d0
' Original Path: /diagrams.puml
' Source: World of Code

@startuml
node client_machine as "Machine utilisateur" {
  agent client as "Navigateur"
}
cloud Internet
node gmail_server as "Machine Serveur" {
  node http_server as "Serveur HTTP" {
    component webmail as "Webmail"
  }
  database mailboxes as "Boîtes emails" {
    artifact mailbox as "maboite@gmail.com"
  }
  node smtp_server as "Serveur SMTP" {
    node smtp_receiver as "Récepteur SMTP"
    queue q1 as "File d'attente"
    node smtp_sender as "Émetteur SMTP"
  }
}

client -- Internet : HTTPS
webmail -- mailbox
Internet -- webmail : HTTPS
webmail -- smtp_receiver
smtp_receiver -- q1
q1 -- smtp_sender
smtp_receiver -- mailbox
Internet -- smtp_sender : SMTP
Internet -- smtp_receiver : SMTP
@enduml
