' Blob ID: 2a4fb22f394f37304773fedd84f53db3aefbe76b
' Original Path: /puFileV7TMS/GenericIdentification72.pu
' Source: World of Code

@startuml
object GenericIdentification72 {
Identification [1...1] : Max35Text
Issuer [0...1] : PartyType6Code
Country [0...1] : Min2Max3AlphaText
ShortName [0...1] : Max35Text
}
@enduml 
