' Blob ID: 2bc41df4d4667c5eb0eb93b7039a8eb927f9190a
' Original Path: /UMLDemo/src/main/uml/活动图.puml
' Source: World of Code

@startuml
start 
:Hello word;
:this is on defined on;
if(成功) then
:是的;
else
:不是的;
endif
:花花;
@enduml
