' Blob ID: 2c70072db295e9ac989eaafadba7223847a12ce1
' Original Path: /Solution.wsd
' Source: World of Code

@startuml
title Solution GetTask

node Azure{
    [ProductivityTools.GetTask3.Reporting]
}


node Windows{
    [ProductivityTools.GetTask3.TomatoTray]
}

node Nuget.org{
    [ProductivityTools.GetTask3.Contract]
    [ProductivityTools.GetTask3.CoreObjects]
}

node PowershellGallery.com{
    [ProductivityTools.GetTask3.Cmdlet]
}


node [productivitytools.tech]{
    [ProductivityTools.GetTask3.Server]
    database "SQL\n" {
    [Data]
    }
}


 [ProductivityTools.GetTask3.Cmdlet] -down->[ProductivityTools.GetTask3.Contract]
 [ProductivityTools.GetTask3.Contract] -down->[ProductivityTools.GetTask3.Server]
 [ProductivityTools.GetTask3.Server] -down->[Data]
 [ProductivityTools.GetTask3.CoreObjects] -[ProductivityTools.GetTask3.Contract]
 [ProductivityTools.GetTask3.CoreObjects] -[ProductivityTools.GetTask3.Cmdlet]
 [ProductivityTools.GetTask3.CoreObjects] -[ProductivityTools.GetTask3.Server]
@enduml
