' Blob ID: 2c8d0ba6f0301ce8f63da39aa57f180b77a85cab
' Original Path: /src/main/resources/ex41/ActivityDiagrams/Sort.puml
' Source: World of Code

@startuml
'https://plantuml.com/activity-diagram-beta

start
    :Get name collection;
    :Compare each lastName in name collection with each other;
    :Collect compared names in ascending order in list;
    :Return List;

@enduml
