' Blob ID: 2daf7be9936c192868bb2fd63b5d7297ac7eeb95
' Original Path: /uml/activity/example5.wsd
' Source: World of Code

@startuml

(*) --> if "Some Test" then
  -->[true] "activity 1"
  if "" then
	-> "activity 3" as a3
  else
	if "Other test" then
	  -left-> "activity 5"
	else
	  --> "activity 6"
	endif
  endif
else
  ->[false] "activity 2"
endif

a3 --> if "last test" then
  --> "activity 7"
else
  -> "activity 8"
endif

@enduml
