' Blob ID: 31110bb0f1bf42b4250695bdcc48d719dd60dc04
' Original Path: /demo/徐林/需求分析/各部分的活动图/测试部分.wsd
' Source: World of Code

@startuml
start
repeat:测试人员填写《软件测试方案》;
    :质量部人员审核测试方案并
    填写《测试方案评审表》;
backward:测试人员根据评审表
完善测试方案;
repeat while(测试方案是否通过) is(不通过) 
:测试人员搭建测试环境并实施测试;
:测试人员填写《软件测试问题清单》;
:测试人员对软件文档测试并
填写《软件文档评审表》;
repeat:测试人员编制测试报告并填写《软件测试报告》;
:质量部人员填写《测试报告检查表》;
backward:测试人员
完善测试报告;
repeat while(测试报告是否通过) is(不通过) 
:市场部人员填写《软件项目委托测试工作检查表》;
:生成正式测试报告并由市场部人员签发;
stop
@enduml
