' Blob ID: 341e57119c73d3e42b67526a5809561a16ef13cb
' Original Path: /test3/two.puml
' Source: World of Code

@startuml
object 读者{
姓名：傲天
学号：201510414327
借书号：20150001
密码：668449
已借图书：Java
未还图书：Java
预约图书：C++
}
newpage
object 图书管理员{
帐户名：admin
密码：admin
}
newpage
object 系统管理员{
帐户名：root
密码：root
}
newpage
object 图书{
ISBN：16810001
名称：Java
类别：编程
作者：Bob
价格：45￥
出版社：教育出版社
存货量：30
}
newpage
object 借还记录{
借书号：20150001
借书ISBN：16810001
借书时间：2015-12-21
借书时长：7天
归还时间：未还
}
newpage
object 违规罚款{
违规账户：20150001
违规原因：未按时归还图书
违规时间：2015-12-28
罚款金额：20￥
}
newpage
object 续借图书{
续借账户：20150001
续借书籍：Java
续借时间：2015-12-28
续借时长：7天
}
newpage
object 预定图书{
预定账户：20150001
预定图书：C++
预定时间：2015-12-21
预定时长：7天
}
newpage
object 订单管理{
订单名称：20150001违规罚款订单
订单描述：20150001超时违规处罚
创建时间：2015-12-28
销毁时间：2016-1-1
}
@enduml
