' Blob ID: 35906bbe4d18f24542b8ec1c0a33284f83eda3d9
' Original Path: /doc/make.puml
' Source: World of Code

@startuml
:Start Gradle;
:s = new Settings();
if (file "settings.gradle" exists) then (yes)
:Process the file "settings.gradle"
Generate the class "settings_b0j4yjuhmbkj9592u1z6fmfuz";
#AAAAAA:Class "settings_b0j4yjuhmbkj9592u1z6fmfuz"]
note left
This class does not contain any "Main" method.
end note
:Use the generated class to configure the Settings object (s).;
else (no)
endif
:p = new Project();
:Process the file "build.gradle"
Generate the class "build_2vd8uxaxzlwimbqukyqr82d63";
#AAAAAA:Class "build_2vd8uxaxzlwimbqukyqr82d63"]
note left
This class does not contain any "Main" method.
end note
:Use the generated class to configure the Project object (p).;
@enduml

