' Blob ID: 36f92a5c67381fc53ef46f8a08f10de16e15ce86
' Original Path: /puFileV7TMS/PointOfInteractionCapabilities6.pu
' Source: World of Code

@startuml
object PointOfInteractionCapabilities6 {
CardReadingCapabilities [0...*] : CardDataReading5Code
CardholderVerificationCapabilities [0...*] : CardholderVerificationCapability4Code
PINLengthCapabilities [0...1] : Number
ApprovalCodeLength [0...1] : Number
MaxScriptLength [0...1] : Number
CardCaptureCapable [0...1] : TrueFalseIndicator
OnLineCapabilities [0...1] : OnLineCapability1Code
MessageCapabilities [0...*] : DisplayCapabilities4
}
@enduml 
