' Blob ID: 3775fce982008ae1b46db1ae2de51e34f1f42c27
' Original Path: /assets/WebDisplayContacts.puml
' Source: World of Code

@startuml

title Web Display Contacts

object Activity
object ActivityNegotiator
object ActivityDepartment
object User
object OrganisationalUnit

object WebDisplayContact
object GenericMarketingContact

ActivityDepartment --|> OrganisationalUnit 
ActivityNegotiator --|> User 
ActivityNegotiator --|> Activity
ActivityDepartment --|> Activity

GenericMarketingContact --|> OrganisationalUnit

WebDisplayContact --|> Activity
WebDisplayContact --|> ActivityNegotiator
WebDisplayContact --|> GenericMarketingContact

User : Id
User : FirstName
User : LastName
User : EmailAddress
User : TelephoneNumber

ActivityDepartment : Id
ActivityDepartment : ActivityId
ActivityDepartment : DepartmentId

ActivityNegotiator : Id
ActivityNegotiator : ActivityId
ActivityNegotiator : UserId

Activity : Id
OrganisationalUnit : Id

WebDisplayContact : Id
WebDisplayContact : ActivityId
WebDisplayContact : Order
WebDisplayContact : ActivityNegotiatorId
WebDisplayContact : GenericMarketingContactId

GenericMarketingContact : Id
GenericMarketingContact : DepartmentId
GenericMarketingContact : FirstName
GenericMarketingContact : LastName
GenericMarketingContact : EmailAddress
GenericMarketingContact : TelephoneNumber

@enduml
