' Blob ID: 40153552629f53f92a37cc2c5650a8a08b05f216
' Original Path: /exercise/f.Timimg/j.more.plantuml
' Source: World of Code

@startuml

robust "Third Party" as TP
robust "Back End" as BE
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle
BE is Idle

@100
WU -> WB : http://web-page-1
WU is Waiting
WB is Processing

@300
WB -> BE : http://endpoint-1
BE is Processing
WB is Waiting

@400

BE -> WB@+50
WB@+100 -> WU@+100: redirection

@550
WU -> WB : http://web-redirection-page
WU is Working
WB is Waiting
BE is Idle


@600
WB@600 -> TP:
TP is Working
WU is Waiting
@700
TP -> WB
WB@+50 -> BE@+50
BE is Processing
BE@+50 -> TP@+50
TP@+55 -> BE@+55
BE@+55 -> WB@+55
WB@+55  -> WU@+55
WU is Working

@800

@enduml
