' Blob ID: 40f06d1112d77659d521762da2025426c2d31c71
' Original Path: /diagrams/productstroom.puml
' Source: World of Code

@startuml
:Plan van aanpak & Werkafspraken;

fork  
  :Onderzoek;
fork again
  :Onderzoek;
end fork

  :Functioneel ontwerp;
fork
  :Technisch ontwerp;
fork again
  :Testplan / Testrapport;
end fork
  :App;

  :Retrospective;
@enduml
