' Blob ID: 439701590e7781ad945589f1c006ad78eaabb891
' Original Path: /.docs/usecase.puml
' Source: World of Code

@startuml
skinparam monochrome true

left to right direction

actor "System administrator" as s_admin
actor "Theater administrator" as t_admin
actor User as user
actor "Film‐distributing agency" as agency

package "maintenance" {
    s_admin -- (Create theater ID)
    s_admin -- (Create agency ID)
    (Create theater ID) -- t_admin
}

package "agency-administration" {
    (Create agency ID) -- agency
    agency -- (Login agency)
    (Create theater ID) -- (Search theater ID)
    agency -- (Search theater ID)
    agency -- (Add movie)
    agency -- (Edit movie)
    agency -- (Delete movie)
}

package "theater-administration" {
    t_admin -- (Login theater admin)
    t_admin -- (Edit theater)
    t_admin -- (Create screen)
    t_admin -- (Edit screen)
    t_admin -- (Delete screen)
    t_admin -- (Set movie to screen)
    (Add movie) -- (Set movie to screen)
}

package "portal" {
    (Edit theater) -- (Search theater)
    (Search theater) -- user
    (Set movie to screen) -- (Search movie)
    (Search movie) -- user
    (Reserve movie) -- user
}

@enduml
