' Blob ID: 46c87c7251c9309778f503d964b619d583a0fbb8
' Original Path: /test3/object3.puml
' Source: World of Code

@startuml
    object 图书管理员{
        职工号
        姓名
    }
    object 学生图书管理员{
        身份证号=123123
        姓名="刘继"
    }
    object 系统管理员{
        职工号=0001
        姓名="张继科"
    }
    图书管理员 <|-- 学生图书管理员
    图书管理员 <|-- 系统管理员
    系统管理员 "1"-- "1..*"学生图书管理员
    @enduml
