' Blob ID: 4a584dc2e8838aee16b586f91308dc9e852c4a6e
' Original Path: /requirements/useCase/actorDiagram.puml
' Source: World of Code

@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor Player as player
usecase "Start" as start
usecase "Propose" as propose
usecase "Restart" as restart
usecase "showBoard" as showBoard
player --> start
start ..> showBoard :include
player --> propose
propose ..> showBoard :include
player --> restart
@enduml
