' Blob ID: 4f97bcce4410c15d0aac25d7f71163d55e7efbd4
' Original Path: /thingml-gen/uml/base/POT_POT.plantuml
' Source: World of Code

@startuml
skinparam defaultTextAlignment left
caption Behavior of thing POT
[*] --> POT
state POT{
state READY_1{
	READY_1 : clock?ms25_tic / \naction ...\n
}
[*] --> READY_1
}
@enduml
