' Blob ID: 5165eec851df7d5455b975a99baedae99422ff4a
' Original Path: /notes/fsm/adbg/tap-top/tap-top.uml
' Source: World of Code

'	This PlantUML script is written by Zhiyang Ong for drawing FSM of advanced debug unit's TAP.

'	The MIT License (MIT)

'	Copyright (c) <2017> Zhiyang Ong

'	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

'	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

'	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

'	Email address: echo "cukj -wb- 23wU4X5M589 TROJANS cqkH wiuz2y 0f Mw Stanford" | awk '{ sub("23wU4X5M589","F.d_c_b. ") sub("Stanford","d0mA1n"); print $5, $2, $8; for (i=1; i<=1; i++) print "6\b"; print $9, $7, $6 }' | sed y/kqcbuHwM62z/gnotrzadqmC/ | tr 'q' ' ' | tr -d [:cntrl:] | tr -d 'ir' | tr y "\n"		Don't compromise my computing accounts. You have been warned.



/'
 ' Drawing FSM of advanced debug unit's TAP.
 '/
@startuml

'	Dummy state transition, or declaration of initial node to declare the figure as a FSM, rather than a sequence diagram.
[*] --> test_logic_reset

test_logic_reset --> test_logic_reset : tms_pad_i
test_logic_reset --> run_test_idle : else

run_test_idle --> select_dr_scan : tms_pad_i && (passchk)
run_test_idle --> run_test_idle : else and conditionally update 'passchk'

select_dr_scan --> select_ir_scan : tms_pad_i
select_dr_scan --> capture_dr : else

capture_dr --> exit1_dr : tms_pad_i
capture_dr --> shift_dr : else

shift_dr --> exit1_dr : tms_pad_i
shift_dr --> shift_dr : else

exit1_dr --> update_dr : tms_pad_i
exit1_dr --> pause_dr : else

pause_dr --> exit2_dr : tms_pad_i
pause_dr --> pause_dr : else

exit2_dr --> update_dr : tms_pad_i
exit2_dr --> shift_dr : else

update_dr --> select_dr_scan : tms_pad_i
update_dr --> run_test_idle : else

select_ir_scan --> test_logic_reset : tms_pad_i
select_ir_scan --> capture_ir : else

capture_ir --> exit1_ir : tms_pad_i
capture_ir --> shift_ir : else

shift_ir --> exit1_ir : tms_pad_i
shift_ir --> shift_ir : else

exit1_ir --> update_ir : tms_pad_i
exit1_ir --> pause_ir : else

pause_ir --> exit2_ir : tms_pad_i
pause_ir --> pause_ir : else

exit2_ir --> update_ir : tms_pad_i
exit2_ir --> shift_ir : else

update_ir --> select_dr_scan : tms_pad_i
update_ir --> run_test_idle : else









@enduml
