' Blob ID: 5259b5b0b87f218108124ace14ed217647a17add
' Original Path: /1.design/3.robustnesses/book_update_isbn.puml
' Source: World of Code

@startuml

' ----------- meta

title: 書籍情報（ISBN）を更新する

skinparam {
  ControlFontColor<<error>> white
  ControlFontName<<error>> Verdana
  ControlBackgroundColor<<error>> gray
  ControlBorderColor<<error>> black
}

' left to right direction

actor User
boundary book_list as "書籍一覧画面"
control list_book
boundary book_info as "書籍情報画面"
control find_book
boundary book_edit as "書籍更新画面"
control update as "更新する"
control amazon as "Amazon API"
entity book

note top of book_info
  書籍情報
  ====
  書籍名(title)
  ISBN
  期待(expectation)
  章・節(section)
    期待(expectation)
    疑問(question)
    考え(thought)
    理解(learning)
end note

' ----------- main

User --- book_list
book_list <-- list_book : 書籍リストを表示
book_list --> book_info : 書籍名をタップする
book_info <-- find_book : 書籍情報を表示
book_info --> book_edit : 編集ボタンを\nタップする
book_edit --> update : ISBNを入力する
update <-- amazon : 書籍情報を取得する
update --- book : 書籍情報を保存する
update --> book_info : 完了


' ----------- alternative
control error400 <<error>>
note top of error400
    400 Bad Request を返す
end note

save --> error400 : 書籍名の長さがゼロ

@enduml
