' Blob ID: 5402adb1b50b888c25f5d5ec161ecee5f4c05b22
' Original Path: /puFileV7acq/CardPaymentDataSetTransaction24.pu
' Source: World of Code

@startuml
object CardPaymentDataSetTransaction24 {
TransactionSequenceCounter [1...1] : Max9NumericText
Traceability [0...*] : Traceability5
Environment [1...1] : CardPaymentEnvironment68
Context [0...1] : CardPaymentContext26
Transaction [1...1] : CardPaymentTransaction81
}
@enduml 
