' Blob ID: 54da32f81e8aaaa5a22cd63b9dc69a72ab60fc73
' Original Path: /assets/vesc_tx.plantuml
' Source: World of Code

@startuml
robust "VESC" as VESC
concise "UART Bytes" as UARTb
concise "UART Command" as UARTc

@0
VESC is idle
UARTb is idle
UARTc is idle

@20
VESC is tx
UARTb is 2
UARTc is type

@40
VESC is tx
UARTb is 1
UARTc is length

@60
VESC is tx
UARTb is 0
UARTc is cmd

@80
VESC is tx
UARTb is payload...
UARTc is payload...

@120
VESC is tx
UARTb is crc
UARTc is crc

@140
VESC is tx
UARTb is 3
UARTc is 3

@160
VESC is idle
UARTb is idle
UARTc is idle


@enduml
