' Blob ID: 57f92c5aac893469250bbbd698956d2c5ec96b10
' Original Path: /src/cleonproject.deliverables.architecture.model.architecture/src/cleon.architecturemethods.itarc42.sample/img/cleon_architecturemethods_itarc42_ikt/Bausteinabh_ngigkeitsdiagramm_Endpoint_Protection_Orchestrator__EPO___SystemConfiguration___Blackbox_.puml
' Source: World of Code

@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Endpoint__F_Protection__F_Orchestrator__F___N_EPO__O_ as "Endpoint Protection Orchestrator (EPO)" <<$lock_with_key_security>> {
}

rectangle Windows__F___N_WIN__O_ as "Windows (WIN)" <<$windows_server>> {
}
Endpoint__F_Protection__F_Orchestrator__F___N_EPO__O_ -down-> Windows__F___N_WIN__O_ : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,02c3416a-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
