' Blob ID: 5ddf5fe092240e6e75f448b9cbf8a793c15f2ebf
' Original Path: /uml/activity.puml
' Source: World of Code

@startuml
start
repeat
  :read data;
  :generate diagrams;
repeat while (more data?)
stop
@enduml
