' Blob ID: 6337fb35df301c523b18d9cced59b9cd7515aa25
' Original Path: /РегистрыСведений/РегистрСведенийЗаданияКРасчетуОчередиПроизводственныхОпераций.wsd
' Source: World of Code

﻿@startuml
'!include templates.wsd
'..\include templates.wsd
class РегистрСведений.ЗаданияКРасчетуОчередиПроизводственныхОпераций as "Задания к расчету очереди производственных операций" <<РегистрыСведений>>
{
..Измерения..
ОбъектРасчета : Документ.Этап производства
Идентификатор : Уникальный идентификатор
ДеньРегистрации : Число 7, 0
}
@enduml
