' Blob ID: 64fb9bfe684b5f3978f265cacefad2d86f45cf69
' Original Path: /.draft/阅读笔记/.归档技术笔记/Language/java/collection/img/basic.puml
' Source: World of Code

@startuml

interface Iterator<E> {
  E next();
  boolean hasNext();
} 

interface Iterable<E> {
  Iterator<E> iterator();
}

Iterable ..> Iterator: produce >

interface Collection<E> {
}

Collection --|> Iterable

class AbstractCollection<E>

AbstractCollection --|> Collection


@enduml
