' Blob ID: 65a804a3631290e37cebd547fd685a36f34b383a
' Original Path: /document/uml/deploymentCloudRun.plantuml
' Source: World of Code

@startuml

actor Player
cloud "GCP" {
  rectangle "US-Central" {
    node "Virtual Machine" {
      component "Blog Server" as Blog
    }
    node "Cloud Run" as RunUC {
      component "JaPong Server" as JaPongUC {
        component "Room Management" as RoomManagementUC
        component "Game Management" as GameManagementUC
      }
    }
  }
  rectangle "Asia-Northeast" {
    node "Cloud Run" as RunAN {
      component "JaPong Server" as JaPongAN {
        component "Room Management" as RoomManagementAN
        component "Game Management" as GameManagementAN
      }
    }
  }
}

Blog <-- Player: 1
RoomManagementAN <-- Player: 2
GameManagementAN <-- Player: 3

@enduml
