' Blob ID: 676cac6bb1d5f22a7f68635562de56842c5c4e80
' Original Path: /plantuml-images/54fd1c628c5b90e0e4b8098d131ea122db695679.uml
' Source: World of Code

@startuml
title list notes

start
if (Directory option listed?) then (yes)
    :set directory to supplied path;
else (no)
    :set directory to ./;
endif
if (notebook.yml exists and is valid) then (yes)
  :Load options from notebook.yml and merge with defaults;
  while (Unlisted notes in nootbook) is (not empty)
    if (Note meets filter) then
      :List note;
    endif
  endwhile
endif
:Print results;
stop
@enduml
