' Blob ID: 6b8751e49e0146579102eec2e62df8c220657a72
' Original Path: /test/test_readme_file/test7/test-7-multiple-monitors.Monitor1.pu
' Source: World of Code

@startuml
state Monitor1{
  [*] -> __Always__
  state __Always__ #green
  __Always__ --> __Always__ : **event**\nevent == 1
}
@enduml
