' Blob ID: 6f08b6656fd05a5d5c9108013139d3754f674a3e
' Original Path: /Diagrams/Domain_Mode.plantuml
' Source: World of Code

@startuml

object User {
    ID
    Nickname
    Name
    Gender
    Region
    Games
    Credits
}

object UserGame {
    Game
    Level
}

object Game {
    Title
}

object Skill {
    Level
}

User::Games --> UserGame
UserGame::Game --> Game
UserGame::Level --> Skill

@enduml
