' Blob ID: 714dfa75310061957a92233cb37ae3249feb6314
' Original Path: /RaceHelper/UML/SequenceRegister.uml
' Source: World of Code

﻿@startuml

actor User

User -> Program : Register(\n name, birthYear, \n club, gender)
Program -> Participant: new Participant(\n name, birthYear, \n club, gender)
Participant -> Run: genderObj = \n GetGender(gender)
Participant -> Run: ageGroupObj = \n GetAgeGroup(birthYear)
Participant -> Run: clubObj = \n GetOrCreateClub(club)



@enduml
