' Blob ID: 72508ba9f51df3385382d54057e035c4cc698fc7
' Original Path: /uml/models.uml
' Source: World of Code

@startuml
object Space {
  A space object refers to a physical location.\nSpaces include neighborhood parks and large \ncity-maintained green belts.
  ----
  space_id text NOT NULL,
  name text NOT NULL,
  lat double precision NOT NULL,
  long double precision NOT NULL,
  address text NOT NULL,
  phone_number text NOT NULL,
  url text NOT NULL,
  open_hours text[] NOT NULL,
  types text[] NOT NULL,
  rating double precision,
  photos text[],
  PRIMARY KEY (space_id)
}

object Weather {
  A weather object refers to a weather forecast in a 3 hour period.\nSpaces have many of these weather objects, \nwhile a single weather object refers to only a single space.
  ----
  weather_id serial NOT NULL,
  space_id text NOT NULL REFERENCES spaces(space_id) DEFERRABLE,
  high text NOT NULL,
  low text NOT NULL,
  local_date date NOT NULL,
  local_time time NOT NULL,
  description text NOT NULL,
  icon_id text NOT NULL,
  PRIMARY KEY (weather_id)
}

object Review {
  A review object refers to a user review of a physical location.\nSpaces have many of these review objects, while a single review \nobject refers to only a single space.
  ----
  review_id serial NOT NULL,
  space_id text NOT NULL REFERENCES spaces(space_id) DEFERRABLE,
  name text NOT NULL,
  rating double precision NOT NULL,
  photo text,
  url text,
  time text NOT NULL,
  body text NOT NULL,
  PRIMARY KEY (review_id)
}

object Event {
  An event object refers to a physical gathering of people. \nEach event will occur in a single space and has a single associated group.
  ----
  event_id text NOT NULL,
  space_id text NOT NULL REFERENCES spaces(space_id) DEFERRABLE INITIALLY IMMEDIATE,
  group_id text NOT NULL REFERENCES groups(group_id) DEFERRABLE INITIALLY IMMEDIATE,
  name text NOT NULL,
  rsvp_limit integer NOT NULL,
  rsvp_count integer NOT NULL,
  status text NOT NULL,
  local_date date NOT NULL,
  local_time time NOT NULL,
  venue_name text NOT NULL,
  venue_address text NOT NULL,
  link text NOT NULL,
  description text NOT NULL,
  how_to_find_us text NOT NULL,
  category text[] NOT NULL,
  photo text NOT NULL,
  description_tags text[] NOT NULL,
  PRIMARY KEY (event_id)
}

object Group {
  A group object refers to a collection of individuals. \nGroups host many events, and so they have many \nevent objects.
  ----
  group_id text NOT NULL,
  name text NOT NULL,
  status text NOT NULL,
  link text NOT NULL,
  url_name text NOT NULL,
  description text NOT NULL,
  creation_time bigint NOT NULL,
  categories text NOT NULL,
  join_mode text NOT NULL,
  city text NOT NULL,
  country text NOT NULL,
  member_count integer NOT NULL,
  organizer_name text NOT NULL,
  organizer_bio text NOT NULL,
  organizer_photo text NOT NULL,
  group_photo text NOT NULL,
  PRIMARY KEY (group_id)
}

' Spaces have many weather objects
Space "1" *- "many" Weather
' Spaces have many review objects
Space "1" *- "many" Review

' Events have a single space object
' Spaces have many event objects
Event "many" -* "1" Space
' Events have a single group object
' Groups have many Event objects
Event "many" -* "1" Group
@enduml
