' Blob ID: 74168e443c06eb2e1ee3764636da51722d64ed15
' Original Path: /Chapter07/docs/Diagrams/deduplication_flow.puml
' Source: World of Code

@startuml
'https://plantuml.com/activity-diagram-beta
!theme plain
skinparam dpi 400
skinparam defaultFontName Jetbrains Mono

start
:Start Transaction;
:Add MessageID to Store;
if (MessageID added) then (success)
  :Process Message;
  if (Success?) then (yes)
    :Commit;
  else (no)
    :Rollback;
  endif
else (conflict)

endif
stop

@enduml
