' Blob ID: 743259405358fc1a7014429521e5f9a64ff6f325
' Original Path: /documents/analyse_uml/diagramme_de_sequence/diagramme_sequence_reponse/diagramme_sequence_voireponse.wsd
' Source: World of Code

@startuml
autonumber 
actor Administrateur #Black
Administrateur -> Reponse : Afficher interface réponse
activate Reponse #SkyBlue
Reponse --> Administrateur : Interface affichée
deactivate Reponse
alt #GreenYellow Cas valide 
Reponse <-- Administrateur : Accès à la page d'administration réponse
else #IndianRed Cas problème
Reponse --> Administrateur : Erreur server redirection sur la page d'accueil
end
Reponse -> Voir : Redirection sur la page
Voir -> Validation : Afficher interface voir une réponse
activate Validation #SkyBlue
Validation --> Voir : Interface affichée
deactivate Validation
alt #GreenYellow Cas valdide 
Voir --> Validation : Redirection à la page voir une réponse
else #IndianRed Cas problème
Voir <-- Validation : Erreur server redirection sur la page d'accueil
end
@enduml
