' Blob ID: 74f0bcff5642b2a7c6e641c7c04c25b5c003802c
' Original Path: /passenger-demo/passenger.plantuml
' Source: World of Code

@startuml
' CoolTheme
'------------------------------------
' Defining skin parameters
'------------------------------------

skinparam BackgroundColor transparent
skinparam class {
    BackgroundColor WhiteSmoke
    BorderColor DimGray
    ArrowColor Black
    
    FontColor DarkSlateGray
    FontSize 18
    FontName Aapex
    FontStyle bold
    
    AttributeFontSize 18
    AtrributeIconSize 20
    AttributeFontColor DarkSlateGray
}

'------------------------------------
' Start drawing from here
'------------------------------------

scale 1.5

enum SafeRestrictions{
    + SUV_MAX_SPEED = 150
    + CAR_MAX_SPEED = 180
}

class ContactInfo{
    - _name
    - _address
    - _phone
    - _license
    + save()
    + get()
}

class MotorVehicle {
    - _num_of_wd: Integer
    - _model: String
    - _plate: String
    - _speed: Integer
    - _max_speed: Integer
    + set_speed(speed: Integer)
    + moving()
    + get_model()
}

class Suv{
    - _max_speed: SUV_MAX_SPEED
}

class Car{
    - _max_speed: CAR_MAX_SPEED
}

class Passenger{
    - _contact_info: ContactInfo
    + drive(vehicle: MotorVehicle, speed: Integer)
    + fill_contact_info()
    + show_contact_info()
}

Car ..|> MotorVehicle
Suv ..|> MotorVehicle
Passenger ..> Car
Passenger ..> Suv
Passenger -up-> ContactInfo

@enduml
