' Blob ID: 751c453b831e01125ba030c2b1da321d84d651b3
' Original Path: /paper/source/meth/uc-anal-design/uml/p-member-add-assistant.puml
' Source: World of Code

@startuml
hide footbox
autoactivate on
skinparam sequenceParticipant underline
actor ":User" as usr
boundary ":Invite Member Form" as form
control ":Project Controller" as ctl
entity ":User" as db_usr

usr -> form : // enters invited member's name()
form -> ctl : // send form()
ctl -> db_usr : // check new user's role()
ctl <-- db_usr : // new user is an assistant
form <-- ctl
usr <-- form : // inform that added user is an assistant
@enduml
