' Blob ID: 78c48b855bbcae72d9ccd6dea408ca0bd810e6a1
' Original Path: /DiagramasActividad/DiagramaDeActividad.puml
' Source: World of Code

@startuml
|Administrador|
start
:Ha ejecutado el CU014(Buscar avanzado producto) con éxito;
:Selecciona el producto que desea modificar;
|ZMGestion|
repeat
repeat
repeat
repeat
:Muestra un formulario autocompletado con los datos del producto
seleccionado para que el administrador modifique nombre, tipo de producto, categoría, grupo,
cantidad de tela necesaria y precio. Indicando que todos los campos son obligatorios, exceptuando por la
cantidad de tela necesaria;
|Administrador|
:Modifica los campos que desea cambiar;
|ZMGestion|
repeat while(Alguno de los campos requeridos se encuentra vacío) is (V)
repeat while(El nombre, grupo y categoría ingresados ya estan en uso) is (V)
repeat while(El precio es menor o igual que cero) is (V)
repeat while(La cantidad de tela necesaria es menor que cero) is (V)
:Modifica el producto con los datos ingresados y muestra un mensaje idnicando el éxito de la operación;
|Administrador|
end
@enduml
