' Blob ID: 7bf065b56ced4129b68ded0be30efe9170539e27
' Original Path: /Proyecto/Servidor_rbpi/UMLs/mensajes.puml
' Source: World of Code

@startuml

package "Mensaje" {
interface MSJ
[State]
[Comandos]
[Latido]
}

package "Gestor VideoWalls" {
GUI - "3"[Sockets IN/OUT]
}

package "Servidor Rbpi" {
VLC -"3" [Sockets IN/OUT 2]
}

[Sockets IN/OUT] --> MSJ
[Sockets IN/OUT 2] --> MSJ


@enduml
