' Blob ID: 7c5999beda75ab63971d20dea1400cc78152d979
' Original Path: /ems-doc/uml/use_cases.puml
' Source: World of Code

@startuml

rectangle Station {

    actor Dispatcher as Dis
    actor :Station Doctor: as SDoc
    actor :Chief Doctor: as CDoc

    SDoc -right-|> Dis
    CDoc -right-|> SDoc
}

rectangle EMS {

    Dis --> (add Call)
    Dis --> (assign Call)
    Dis --> (set Call Status)
    Dis --> (monitor active Calls)
    Dis --> (monitor active Crews)
    Dis --> (monitor Crews' location)
    Dis --> (finished Calls listing)
    Dis --> (add Crew)
    Dis --> (remove Crew)

    (add Call) --> (assign Call)
    (assign Call) --> (set Call Status)
}

newpage

rectangle Crew {
    actor Doctor as Doc
    actor Assistant as As
    actor Attendant as At
    actor Driver as D
}

rectangle EMS-Mobile {

    Crew --> (receive Call info)
    Crew --> (receive Call location)
    Crew --> (change Crew Status)
    Crew --> (set Call Status:\nMOVING, \nFINDING, \nTREATMENT, \nTRANSPORTATION, \nFINISHED)
}

@enduml
