' Blob ID: 8079cc93f24862c0caa603e00fce1bc1da687e4f
' Original Path: /Tactiques/redondance-active/exercice-DS-redondance.puml
' Source: World of Code

@startuml
skinparam style strictuml 
Actor "vote:IVote" as IV
participant "monitor:IMonitorCtrl" as IMC
participant "map<id,Sommateur>" as map
participant "sommateur[i]:ISommateurCtrl" as ISC
participant "switch:ISommateur" as SW
participant "sommateur:ISommateur" as IS
participant "sommateur:ISommateurCtrl" as ISC
participant "switch:ISwitchCtrl" as ISWC
participant "dataWebServer:IDataWebServer" as IDWS

@enduml
