' Blob ID: 8340e81ea689f15671b60ad8f573ec0b52081094
' Original Path: /architecture-notebook/src/networking/load-balancing/L4-L7-dual-layer.puml
' Source: World of Code

@startuml

cloud "Internet" as IN {
}

package "L4 Load Balancers" as L4 {
[LB\nActive] - [LB\nBackup]
}

package "SSL Termination and Cache Pool" as SSL {
node "SSL_1" as SSL1
node "SSL_2" as SSL2
node "SSL_N" as SSLN
SSL1 . SSL2
SSL2 . SSLN
}

package "L7 Load Balancers" as L7 {
node "Proxy_1" as PX1
node "SSL_2" as PX2
node "SSL_N" as PXN
PX1 . PX2
PX2 . PXN
}

package "Application servers" as APP {
}

IN -> L4
L4 -> SSL
SSL -> L4

@enduml
