' Blob ID: 87ae40a8d5e91f1473443f530cf36c4d3477b1fa
' Original Path: /src/uml/UseCase.puml
' Source: World of Code

@startuml
title Project Use Case
scale max 1920 width
scale max 1080 height


:Committee of data: as cod << People Group >>
:Product Owner: as po
:Project Manager: as pm
:Data Management: as dm << People Group >>
:Data Architect: as da
:Qualif: as qa
:Data Engineer: as den
:Data Analyst: as dan

rectangle Project_Creation {
  (Business Case Evaluation) as (BCE)
  note left of BCE : Stage 1.
}

rectangle Functional_Design\nTechnical_Design {
  (Data Identification) as (DI)
  note left of DI : Stage 2.

  (Data Acquisition & Filtering) as (DAF)
  note left of DAF : Stage 3.

  (Data Extraction) as (DE)
  note left of DE : Stage 4.
}

rectangle Development {
  (Data Agregation & Representation) as (DAR)
  note left of DAR : Stage 5.

  (Data Analysis) as (DA)
  note left of DA : Stage 6.
}

rectangle Test {
  (Unit Test) as (UTS)
  note left of UTS : Stage 7.
  (Integration Test) as (TS)
  note left of TS : Stage 8.
  (Functional Test) as (FTS)
  note left of FTS : Stage 9.
}

rectangle Deployment {
  (Data Visualization) as (DV)
  note left of DV : Stage 10.

  (Utilization of Analysis Results) as (UAR)
  note left of UAR : Stage 11.
}

cod -right- BCE
po -- BCE
pm -down- BCE
pm - DI
dm -up- DI

den -- DAF
den --- DAR
da - DAF
da - DE
da -- DAR

dan -left- DA
qa -down- TS

dan --- DV
dan -- UAR


BCE -down-> DI
DI -down-> DAF
DAF -down-> DE
DE -down-> DAR
DAR -down-> DA
DA -down-> UTS
UTS -down-> TS
TS -down-> FTS
FTS -down-> DV
DV -down-> UAR

@enduml
