' Blob ID: 89af13aadb476163d330f670d3aadc5417e4114c
' Original Path: /doc/ClassDiagram/Client/Client-DB.puml
' Source: World of Code

@startuml

namespace Spider {

namespace Db {

    class DbHandler {
        -mDb : sqlite3
        -mRc : int
        __
        +DbHandler()
        +~DbHandler()
        ..
        +bool   connect(string)
        +void   disconnect()
        +bool   push(Request)
        +Request pop()
        +void   deleteTable()
        +void   showTable()
    }

}
}

@enduml
