' Blob ID: 8c33d753de124cbf51cc3faf2697c2b8da03ca0b
' Original Path: /src/Mastermind/ModelViewPresenter/PresentationModel/Facade/Docs/UseCaseStartView.Plantuml
' Source: World of Code

@startuml
title Use Case Start View

state INITIAL
state IN_GAME
state A as " "
state B as " "

[*] --> INITIAL
INITIAL --> A : Player requests to Start a New Game
A --> B : System show the title and empty Board
B --> IN_GAME : System allows Play
IN_GAME --> [*]
@enduml
