' Blob ID: 8f6ea2a98067bf4c4934ee4c79b368d3c4557e75
' Original Path: /tree.uml
' Source: World of Code

@startuml
[*] --> Initializing
Initializing --> Not_Connected
Not_Connected --> Connected
Connected --> Not_Connected
Connected --> Authentificating_User
@enduml
