' Blob ID: 90b1035e91c585768c45edca6542ecc1bd9e8b96
' Original Path: /schema/user_use_cases.wsd
' Source: World of Code

@startuml
'-------------------------
' User part
'-------------------------
(Use the application) as (Use)
User -> (Login)
User --> (Use)

@enduml
