' Blob ID: 9120267d21bbc896c2bc0cb0d08fc8808a42735b
' Original Path: /Docs/Pflichtenheft/Diagramm/ClientObjektDiagramm.iuml
' Source: World of Code

@startuml
object lukasPeter{
name = "LukasPeter"
birthdate = "27.03.1711"
email = "lukas.peter2703@gmail.com"
phonenumber = " +49 420 1876969"
}

object peter{   
username = "Peter95"
password = "1234Peter95"
}

object tesla{
stockname : name = "Tesla"
value : 778$
}

object menu1{

gson = new Gson()
socket = newSocket(86.234.76.145, 1234)
inputStreamReader = new inputStreamReader 
outputStreamReader = new outputStreamReader
bufferedReader = new bufferedReader
bufferedWriter = new bufferedWriter
account = new Account 

}

peter <|--- lukasPeter
@enduml
