' Blob ID: 92629660d9b18a607083e58fab8782d3c50e6b59
' Original Path: /src/SequenceDiagram.puml
' Source: World of Code

@startuml
!pragma teoz true

{start} Alice -> Bob : start doing things during duration
Bob -> Max : something
Max -> Bob : something else
{end} Bob -> Alice : finish

{start} <-> {end} : some time

@enduml
