' Blob ID: 9648c4bb19d58394c9340187beea0a85907b57bb
' Original Path: /활동.puml
' Source: World of Code

@startuml

title 활동-휴식

state 활성화: 명상(동기반복탑재)
state 활성화: 즉시하기
state 활성화: 시뮬레이션
state 활성화: 문제새로정의(분할)
state 활성화: 5부터1까지
state 비활성화: 대기
state 비활성화: 높은난이도
state 비활성화: 높은피로도

활동 -> 비활성화
휴식중 --> 활성화
비활성화 -> 휴식중
활성화 -> 활동

@enduml
