' Blob ID: 9a2f54946512fefaa8e36c7a69a264b8cb6ae2f1
' Original Path: /doc/uml/cmdb.plantuml
' Source: World of Code


@startuml

skinparam ObjectFontSize 14
skinparam ObjectAttributeFontSize 14

object "Configuration Item \nClass" as ci_class {
    ID
    descirption

}
object "Configuration Item \nClass \nProperty" as ci_class_prop {
    ID
    descirption
    value
    value UoM
}
object "Configuration Item \nProperty" as ci_prop {
    ID
    descirption
    value
    value UoM
}
object "Configuration Item \nRelation" as ci_rel {
    ID
    descirption
    type

}
object "Configuration Item \nRelation\nProperty" as ci_rel_prop {
    ID
    descirption
    value
    value UoM
}

object "Configuration Item"  as ci   {
    ID
    descirption
    CI Class
    hierachy scope
    hierachy level
}

object "hierachy scope" as h_scope {
    ID
    descirption
    hierachy level
    parent
}

enum "hierachy level" as h_level {
    Site
    Building
    Floor
    Room
    Zone
    Rack 
    Rack Unit
}

enum "relation type" as rel_type {
    related_to
    upgrades
    repairs
    impacts
    moves
    installs
    removes
    changes

}

object Asset {
    ID
    descirption
    asset type
    vendor
    purchase date
    asset tag
    location
}

enum "Asset type" {
    software
    hardware
    mixed
    other
}

object "CI Asset Mapping" as ci_asset_mapping {
    ID
    description
    start_date
    end_date
}

ci_class o-- ci_class  : inherit
ci_class  "0..n"-- ci
ci_class *--   ci_class_prop
ci *-- ci_prop
ci - h_level
ci_class_prop  -   ci_prop : map to <
ci - h_scope
h_scope o-- h_scope : nested
h_scope -- h_level : related
ci o-- ci  : left to rgiht
ci --o ci  : right to left
(ci,ci) --  ci_rel :right to left relation
(ci,ci) --  ci_rel :left to right relation
ci_rel *-- ci_rel_prop
ci_rel - rel_type
(ci, Asset) -- ci_asset_mapping
Asset o-- Asset
Asset -- "Asset type"


@enduml
