' Blob ID: 9ae1288cf3d013a141ee100bd2188ecadea5ec0e
' Original Path: /documentation/it01-02/it2_deploy_view.puml
' Source: World of Code

@startuml

' Components
rectangle "1st Iteration" #009FBD {
  
  cloud "az: Azure Cloud Server\n" as az1 #white {
    database "SQL Database" #DCDCDC {
      [MedicinesDB]
    }
    folder "ASP.NET Service" {
      [MedicinesBackend]
    }
}
}

rectangle "2nd Iteration" #43CC72 {

  cloud "az: Azure Cloud Server\n" as az2 #white {
    folder "node.js Service" {
        [ReceiptsFrontend]
    }
  }

  cloud "aws: AWS Cloud Server\n" as aws #white {
    database "MongoDB" #DCDCDC {
        [ReceiptsDB]
    }
  }
}

' Relations
[MedicinesDB] . [MedicinesBackend]
[MedicinesBackend] .. [ReceiptsFrontend]
[ReceiptsFrontend] . [ReceiptsDB] : <back:#FFFFE0>connection</back>\n <img mlab-logo.png>
@enduml
