' Blob ID: 9b22c9e3989be50419e8ad495c3612461fe25dc2
' Original Path: /src/main/java/Diagrams/Activity diagram to be.puml
' Source: World of Code

@startuml

title To be

|Kunde|
if (Kunde hos Fog?) then (Ja)
    :Logger på;
else (Nej)
    :Registrerer;
endif
:Bestiller ordre;

|#AntiqueWhite|System|
:Tilføjer ordre i database;

|Fog|
:Ringer til kunde og giver et tilbud;

|Kunde|
:Betaler på hjemmeside;

|#AntiqueWhite|System|
:Generer teknisk tegning og stykliste;

|Fog|
:Ordre afsendes;

|System|
:Sender teknisk tegning og stykliste m. manual til kunde;


@enduml
