' Blob ID: 9f7b1c31f30a4b5a668a7a9c0c5a41f2077aea16
' Original Path: /recon/modules/relation_analysis.plantuml
' Source: World of Code

@startuml
skinparam classAttributeIconSize 0
' skinparam monochrome true
hide circle
skinparam linetype ortho

ReconModule <|-- RelationAnalysis_SearchModule
class RelationAnalysis_SearchModule{
    void scan()
    void __set_filter(str)
    bool __handle_response(list)
    dict __extract_data(dict)
}

RelationAnalysis_SearchModule <|-- RelationAnalysis_GoogleModule
RelationAnalysis_GoogleModule *-- utility.Google
class RelationAnalysis_GoogleModule{

    {static} Google searchengine
    {static} int MAX_FILTER
    str __str__()
}

RelationAnalysis_SearchModule <|-- RelationAnalysis_BingModule
RelationAnalysis_BingModule *-- utility.Bing
class RelationAnalysis_BingModule{

    {static} Google searchengine
    {static} int MAX_FILTER
    str __str__()
}

@enduml
