' Blob ID: a21b4c8a73a4e2ea112a1891d982a3ea1b6fa90f
' Original Path: /10.0/eapli.framework.core/eapli/framework/actions/menu/MenuItem.puml
' Source: World of Code

@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>MenuItem</b>\n<size:10>eapli.framework.actions.menu" as eapli.framework.actions.menu.MenuItem  [[../../../../eapli/framework/actions/menu/MenuItem.html{eapli.framework.actions.menu.MenuItem}]] {
-String text
-MenuItem(String text)
{static} +MenuItem separator(char symbol,int size)
{static} +MenuItem separator(String label)
{static} +MenuItem of(int option,String text,Action action)
{static} +MenuItem submenu(int option,Menu sub)
+String text()
{abstract} +Optional<Integer> option()
{abstract} +boolean select()
{abstract} +boolean isSubmenu()
{abstract} +Optional<Menu> submenu()
}


class "<b><size:14>Menu</b>\n<size:10>eapli.framework.actions.menu" as eapli.framework.actions.menu.Menu  [[../../../../eapli/framework/actions/menu/Menu.html{eapli.framework.actions.menu.Menu}]] {
}

hide eapli.framework.actions.menu.Menu fields
hide eapli.framework.actions.menu.Menu methods

eapli.framework.actions.menu.Menu -->  "itens *" eapli.framework.actions.menu.MenuItem

eapli.framework.actions.menu.Menu -->  "itemByOption *" eapli.framework.actions.menu.MenuItem

interface "<b><size:14>Action</b>\n<size:10>eapli.framework.actions" as eapli.framework.actions.Action <<FunctionalInterface>> [[../../../../eapli/framework/actions/Action.html{eapli.framework.actions.Action}]] #white {
}

hide eapli.framework.actions.Action fields
hide eapli.framework.actions.Action methods

eapli.framework.actions.menu.MenuItem ..> eapli.framework.actions.Action

eapli.framework.actions.menu.MenuItem ..> eapli.framework.actions.menu.Menu



class "<b><size:14>MenuItemRenderer</b>\n<size:10>eapli.framework.presentation.console.menu" as eapli.framework.presentation.console.menu.MenuItemRenderer <<SuppressWarnings>> [[../../../../eapli/framework/presentation/console/menu/MenuItemRenderer.html{eapli.framework.presentation.console.menu.MenuItemRenderer}]] #white {
}

hide eapli.framework.presentation.console.menu.MenuItemRenderer fields
hide eapli.framework.presentation.console.menu.MenuItemRenderer methods

eapli.framework.presentation.console.menu.MenuItemRenderer ..> eapli.framework.actions.menu.MenuItem



@enduml
