' Blob ID: a297c6dd2277ce04a53379c82b425fc3c72889e0
' Original Path: /docs/Solution/Control/Security/Trust-Manager/Logical.puml
' Source: World of Code

@startuml
rectangle "Diagram TBD"
@enduml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Security/Trust Manager" #lightblue {

    interface "Security/Trust Manager" {
    }

    CLI ()-- "Security/Trust Manager"
    REST ()-- "Security/Trust Manager"
    Web ()-- "Security/Trust Manager"
}

User --> "Security/Trust Manager"
"Security/Trust Manager" --> Used


