' Blob ID: abfb4f32028d7fc13548a225ec9b27360e00615e
' Original Path: /UML/homepage.wsd
' Source: World of Code

@startuml

actor User
boundary UI
control App
control HomePage
control ShowLeague
control fetchLeaguesAll
database store
database API

User -> UI : opens page
UI -> App: request HomePage UI
App -> HomePage: request HomePage component
HomePage-> fetchLeaguesAll: dispatch API request 
fetchLeaguesAll -> API: HTTP GET request
API -> fetchLeaguesAll : HTTP response
fetchLeaguesAll -> store: updates store
store -> HomePage : allow access to information
HomePage -> ShowLeague : send data of 1 league and request component
ShowLeague -> HomePage: response ShowLeague component
HomePage -> App: response HomePage component
App -> UI: response HTML, CSS and JS
@enduml
