' Blob ID: b3a7f76305a8d1646cc00e7b3491864e18e7bd0b
' Original Path: /src/MarketExposure/003_AddNSB.puml
' Source: World of Code

@startuml

cloud Client {
    component Browser
}

node Application {
    component WebUI AS "Web UI"
    component Host AS "NServiceBus Host"
}

node Database {
    database Orders
    component Queue
}

cloud {
    component CRIMS_API AS "CRIMS API"
}

Browser -- WebUI
Application -- Database
Application -- CRIMS_API

@enduml
