' Blob ID: b552149a0f73c425fb68a8963fbc9b383164d274
' Original Path: /backend/docs/application-start-sequence.puml
' Source: World of Code

@startuml
== Start Processes ==
actor user 
user -> npm  : npm test
npm -> mocha : start()
activate mocha

mocha -> node : start()
activate node   

loop till (healtcheck is ok) || (maxAttempts done)
    create server
    node -> server : start()
    activate server

    == Server Startup ==
    create app
    server -> app : express() 

    mocha -> server: HealtCheck

    server -> dbConnector :connectDB(timeout, recreateFlag)
    activate dbConnector

    alt success case        
        server <- dbConnector: ok()
        
        server -> appLoader: configure(app)
        activate appLoader
        server <- appLoader: ok()
        deactivate appLoader  
    else error case
        server <- dbConnector: fail()
        deactivate dbConnector

        server -> appLoader: configureInErrorMode(app)
        activate appLoader
        server <- appLoader: ok()
        deactivate appLoader  

    end
    server -> app: listen()
    activate app
    == Server started ==        
    mocha <- server: Response
end

== Tests running now ==        
mocha -> server: Start Test Suite 


@enduml
