' Blob ID: ba08fb01df64b88d75bcbdddfeaecc90f913164c
' Original Path: /doc/component.pu
' Source: World of Code

@startuml

package "App Container" {
    node "Python(app)" {
        [Flask(App)]
    }
}

package "App DB Container" {
  database "App Database" {
      [account]
  }
}

package "APi Container" {
    node "Python(api)" {  
        [Flask(Api)]
    }
}

package "Api DB Container" {
  database "Api Database" {
      [user data]
  }
}

[Flask(App)] .. [account] : sql
[Flask(App)] .. [Flask(Api)] : http
[Flask(Api)] .. [user data] : sql

@enduml
