' Blob ID: bb1327811b491e3da83a6e69b7953cffbc8866a8
' Original Path: /docs/uml/states.puml
' Source: World of Code

@startuml
state ordered
state delivered

state Bill {
  state invoiced
  state paid
  invoiced --> paid : paying
}

state Barista {
  state scheduled
  state processing
  state processed

  scheduled --> processing : begin making coffee
  processing --> processed : all coffees done
  processed --> delivered
}

[*] --> ordered : order
ordered --> invoiced : request payment
paid --> delivered
ordered --> scheduled : issue Order
delivered --> [*]
@enduml
