' Blob ID: bc91311ec61410ba6016eeb5015c643387f2b6ec
' Original Path: /switch_2020_g4_devops/docs/sprint2/Domain_ModelSprint2Old.puml
' Source: World of Code

@startuml



title Domain Model
skinparam linetype polyline
object "Family" as fam {
id
name
}

object "Category" as cat {
id
name
}

object Person {
name
identification
vat
address
phoneNumberList
emailAddressList
}

together {

object "Family \nRelationship" as FR {

}

object "Family \nRelation Type" as frt {
designation
}
}

together {

object Account {
balance
description
}

object "Cash \nAccount" as CA {

}

object "Bank \nAccount" as BA{
id
}

object "Credit Card \nAccount" as CCA{
id
}

object "Bank Savings \nAccount" as BSA{
id
}

object "Transaction" as T{
date
value
description
}

}

fam "1..*" -down- "*" cat : used by <
cat "1.."-"1" cat : child of >
fam "1" *-down- "0..1" CA : has >
fam "*" *-left- "*" Person : has members >
fam "*" *-  "1" Person : administered by >
fam *-up- FR : has list >
FR "*" -right- "1"frt : of type >
FR "*" - "1" Person : between >
FR "*" - "1" Person : and >
frt -- frt : inverse >

Person o- Account
CA --> Account
BA --> Account
CCA --> Account
BSA --> Account

T "*" -down- "1" Account : from >
T "*" - "0..1" Account : to >
T "*" -left- "1" cat : has >


@enduml
