' Blob ID: bdd3c66b36106820001d3dcffda1fad0a6b10f4f
' Original Path: /docs/authentication.puml
' Source: World of Code

@startuml

skinparam componentStyle uml2

actor user as "End user"
package flow_a as "Multi-trip insurance" {
    boundary page as "Multi-trip page"
    component view_plan_selection as "Plan selection"
    component view_quick_quote as "Generate quick quote"
    component view_buy_plan as "Buy plan"
}

user --> page
page o-d- view_plan_selection
page o-d- view_quick_quote
page o-d- view_buy_plan

@enduml
