' Blob ID: c45ff31cb8f197af443871faf3f31680bfef8ca6
' Original Path: /.history/surfManeirão_20201015145437.wsd
' Source: World of Code

@startuml

package Util {
  class Request {
    #request: {}
    +get(url)
  }
}

package Client {
  
  interface IInfoPraiaData {
    [key: String]: number
  }

  interface IInfoPraia {
    alturaOnda: IinfoPraiaData
    direçãoOnda: IinfoPraiaData
    alturaOndulação: IinfoPraiaData
    direçãoOndulação: IinfoPraiaData
    períodoOndulação: IinfoPraiaData
    velocidadeVento: IinfoPraiaData
    direçãoVento: IinfoPraiaData
  }

  interface IPrevisãoPonto {
    alturaOnda: Number
    direçãoOnda: Number
    alturaOndulação: Number
    direçãoOndulação: Number
    períodoOndulação: Number
    velocidadeVento: Number
    direçãoVento: Number
  }

  class ApiInfoPraia {
    -parameters: [alturaOnda, direçãoOnda, alturaOndulação, direçãoOndulação, períodoOndulação, velocidadeVento, direçãoVento]
    #request: Class Request
  }

  IPrevisãoPonto -> R
}
package Models {

  interface IUser {
    id: String
    name: String
    email: String
    password: String
  }

  interface ModelUser extends IUser {
    
  }

  enum Position {
    N
    S
    L
    O
  }

  interface IPraia {
    -id: Integer
    -name: String
    -position[1]: Position
    -lat: Integer
    -lng: Integer
    -user: String
  }

  IPraia -> Position

  interface PraiaModel extends IPraia

  class Praia implements PraiaModel
}
package Controllers {}
package Middlewares {}
package Services {}

@enduml
