' Blob ID: c6ab67cb111bba473b31a5a152e62e56aaea8f9f
' Original Path: /gradle-hello-world/src/design/声纹验证流程改造.puml
' Source: World of Code


@startuml
title : 图兰朵 声纹购流程图
(*)  --> "声纹支付"
(*)  --> "扫码支付"

--> " "
--> [neiron]" "
If "是否超过1次失败" then
--> [Yes] "异步上传到"
--> "run command"
else
--> "run command"
Endif
-->(*)


@enduml
