' Blob ID: c7c4ed40f304dd82315e3ba4de5924fa4716deac
' Original Path: /malokhvii-eduard/malokhvii07/doc/plantuml/ua/khpi/oop/malokhvii07/navigation/NavigationMarker.puml
' Source: World of Code

@startuml

    class NavigationMarker [[../ua/khpi/oop/malokhvii07/navigation/NavigationMarker.html]] {
        {static} -serialVersionUID: long
        -id: UUID
        -latitude: Double
        -longitude: Double
        -name: String
        -version: Integer
        +NavigationMarker()
        +getId(): UUID
        +getLatitude(): Double
        +getLongitude(): Double
        +getName(): String
        +setId(UUID): void
        +setLatitude(Double): void
        +setLongitude(Double): void
        +setName(String): void
    }

@enduml
