' Blob ID: c9ccb370c690a094ac2c2c5f0711f83005fd6d6d
' Original Path: /uml/skeleton_comm_diagrams/comm_settler_build_gate1.plantuml
' Source: World of Code

@startuml
left to right direction
title "Settler builds teleport"

rectangle "s: Settler" as s
rectangle "ps: PlayerStorage" as store
rectangle ": Skeleton" as skeleton
rectangle "bill: BillOfMaterial" as bill
rectangle "iron1: Iron" as i1
rectangle "iron1: Iron" as i2
rectangle "water: Water" as w
rectangle "uranium: Uranium" as u

skeleton --down-> s : <<create>>
skeleton --up-> store : <<create>>
skeleton --down-> bill : <<create>>
skeleton --left-> i1 : <<create>>
skeleton --left-> i2 : <<create>>
skeleton --left-> u : <<create>>
skeleton --left-> w : <<create>>
skeleton --down-> bill : AddMaterial(iron1)
skeleton --down-> bill : AddMaterial(iron2)
skeleton --down-> bill : AddMaterial(water)
skeleton --down-> bill : AddMaterial(uranium)
skeleton --left-> s : SetStorage(ps)
skeleton --right-> store : AddBill(bill)

@enduml
