' Blob ID: d00a08d901455ad26ad10466f22777048e8c788a
' Original Path: /Analysis/behavioral/PSSM_staff_fullfilment_cd.puml
' Source: World of Code

@startuml
skinparam monochrome true
'left to right direction
title PSSM Temp Staff Fullfilment\nCommunication Diagram\n

rectangle "Normal Case\nClient Demand, Placement, Fulfillment\n"{

  :Client: as C
  :Contract\nManager: as CM
  :Temp\nEmployee: as TE
  :PSSM\nEmployee: as PE
  rectangle ":Contract" as CO
  rectangle ":Staffing\nRequest" as SR
  rectangle ":Temp\nEmployee" as TEC

  C -> CM : "1. Request Temp Staff"
  CM -up-> CO: "2. validateContract()"
  CM -> SR : "3. createNewStaffingRequest()"
  PE -up-> SR : "8. updateStaffingRequest()"

  PE -> TEC : "9. placeEmployee()\n\
    5. reserveEmployee()\n\
    4. getCandidates()"

  TE <- PE : "6. Negotiate Placement"
  TE -> PE : "7. Placement Agreed"
  CM -> SR : "10. closeStaffingRequest()"
  C <- CM : "11. Notify Client, Request Filled"
}

@enduml
