' Blob ID: e55fbff1c0121a3cba83d9039c9016cadc7c3cf1
' Original Path: /bluemarine2/1.1-ALPHA-1/bluemarine2-modules/it-tidalwave-bluemarine2-ui-javafx/apidocs/it/tidalwave/bluemarine2/ui/impl/javafx/role/FileSystemAudioFileCustomGraphicProvider.puml
' Source: World of Code

@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>FileSystemAudioFileCustomGraphicProvider\n<size:10>it.tidalwave.bluemarine2.ui.impl.javafx.role" as it.tidalwave.bluemarine2.ui.impl.javafx.role.FileSystemAudioFileCustomGraphicProvider [[FileSystemAudioFileCustomGraphicProvider.html]] {
        +getGraphic(): Node
    }

    interface "<size:14>CustomGraphicProvider\n<size:10>it.tidalwave.ui.role.javafx" as it.tidalwave.ui.role.javafx.CustomGraphicProvider {
        {abstract} +getGraphic(): Node
    }

    it.tidalwave.ui.role.javafx.CustomGraphicProvider <|.. it.tidalwave.bluemarine2.ui.impl.javafx.role.FileSystemAudioFileCustomGraphicProvider

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
