' Blob ID: e6ebeb355f3e9f1b7e95281c87cc9c963cc7b792
' Original Path: /document/analysis/robustness-bot-create.puml
' Source: World of Code

@startuml

actor 管理者
boundary ボット追加画面 #green
boundary ボット一覧画面 #green
control ボット追加画面を表示する
control ボット情報を入力する
control ウェブフックURLの形式と重複をチェックする
control ボット名の文字数をチェックする
control アバターのリソースをチェックする
control エラーメッセージを表示する
control アバターのリソースをアップロードする
control ボットを追加する
entity ボット #blue

管理者 --> ボット追加画面
ボット追加画面を表示する --> ボット追加画面
ボット追加画面 --> ボット情報を入力する
ボット情報を入力する --> ウェブフックURLの形式と重複をチェックする :追加ボタンを押す
ウェブフックURLの形式と重複をチェックする --> エラーメッセージを表示する :形式が不正の場合
ウェブフックURLの形式と重複をチェックする --> ボット名の文字数をチェックする
ウェブフックURLの形式と重複をチェックする -- ボット
ボット名の文字数をチェックする --> エラーメッセージを表示する :文字数が不正の場合
ボット名の文字数をチェックする --> アバターのリソースをチェックする
アバターのリソースをチェックする --> アバターのリソースをアップロードする :アバターのリソースが設定されてた場合
アバターのリソースをチェックする --> ボットを追加する :アバターのリソースが無かった場合
アバターのリソースをアップロードする --> ボットを追加する
ボットを追加する -- ボット
エラーメッセージを表示する --> ボット追加画面
ボットを追加する --> ボット一覧画面

@enduml
