' Blob ID: ecfbc5e1d7dbb51721238cacae634109201bece0
' Original Path: /docs/diagrams/src/old-sequence-diagram.puml
' Source: World of Code

@startuml
skinparam BoxPadding 10
title Compass Sequence Diagram

actor "User"
participant "HubSpot"
participant "TypeForm" as TypeForm
participant "TypeForm API" as TypeFormApi
participant "Node App" as NodeApp
box AWS
participant "S3 Bucket" as s3
participant "SES"
end box
User -> HubSpot: Loads Compass
HubSpot -> HubSpot: Generate UUID to identify user
HubSpot -> TypeForm: Load embedded TypeForm survery
User -> HubSpot: Completes survey
TypeForm -> HubSpot: Redirects to HubSpot Landing Page Submission Form\n""https://info.codurance.com/en/compass-details-submission""
User -> HubSpot: Completes submission form
HubSpot -> HubSpot: Save submission info \n& contact in Hubspot
NodeApp <- HubSpot: Redirects to ""/report/submit/:uuid"" (to generate report)
NodeApp -> NodeApp: Start report generation
activate NodeApp
NodeApp -> HubSpot: Redirects to HubSpot Thanks Landing Page\n"""https://info.codurance.com/en/compass-successful-submission"""
NodeApp -> TypeFormApi: Gets survery questions & answers
activate TypeFormApi
NodeApp <--TypeFormApi
deactivate TypeFormApi
NodeApp -> HubSpot: Get user details
note left: generate report \n and send email
activate HubSpot
NodeApp <-- HubSpot
deactivate HubSpot
NodeApp -> NodeApp: Build report and render with jsreport
NodeApp -> s3: Upload report to AWS S3 bucket
NodeApp -> s3: Query report link
activate s3
NodeApp <-- s3:
deactivate s3
NodeApp -> NodeApp: Compose email data with report pdf link
NodeApp -> SES: Queue email for sending
deactivate NodeApp
SES -> User: Send email to user
@enduml
