' Blob ID: f55e87c7aa2db98713078adf4ce65c83af8e5882
' Original Path: /목표상태.puml
' Source: World of Code

﻿@startuml

title 시간에 따른 목표상태

state "집" as jip1 {
  state 일어나기: 스케쥴확인
  [*] -> 시간확인
  시간확인 -> 일어나기
  일어나기 -> 씻기
  씻기 -> 옷입기
  옷입기 -> [*]
}


state 회사 {
  state "휴식" as hu1
  [*] -> 업무파악
  업무파악 --> 업무
  업무 -> 점심
  점심 -> 업무
  업무 -> 저녁
  업무 -> hu1
  점심 --> hu1
  hu1 -> 점심
  hu1 -> 업무
  업무 -> 부가활동
  hu1 --> 부가활동
  저녁 --> 부가활동
  업무 --> [*]
  부가활동 -> [*]
  hu1 --> [*]
  저녁 --> [*]
}

state "집" as jip2 {
  state 집안일: 청소
  state 집안일: 설거지
  state 집안일: 빨래
  state 집안일: 빨래개기
  state 집안일: 동물관리
  state 집안일: 식물관리
  state "식사" as j2
  state "휴식" as hu2
  [*] -> 집안일
  [*] -> j2
  [*] --> hu2
  j2 -> 집안일
  집안일 --> hu2
  hu2 -> hu2
  hu2 --> [*]
}

state 자기계발 {
  [*] --> 개발
  [*] --> 투자공부
  [*] --> 메타인지
  메타인지 --> [*]
  개발 --> [*]
  투자공부 --> [*]
}

state 하루마무리 {
  [*] -> 샤워
  샤워 -> 하루피드백
  하루피드백 -> 내일계획
  내일계획 -> [*]
}

state "데이트" as date2 {
  [*] -> 좋은시간
  좋은시간 -> [*]
  state 좋은시간: 식사
  state 좋은시간: 게임
  state 좋은시간: 넷플릭스, 유투브
  state 좋은시간: 영화
  state 좋은시간: 이야기
}

[*] --> jip1: 기상
jip1 -> date2: 주말, 휴일
jip1 -> jip2: 주말, 휴일

jip1 --> 회사: 평일출근
회사 --> date2: 퇴근
회사 --> jip2: 퇴근

jip2 -> date2
date2 -> jip2
jip2 -> 자기계발
자기계발 -> jip2
자기계발 --> 하루마무리
jip2 --> 하루마무리
date2 --> 하루마무리
하루마무리 --> [*]: 취침

@enduml
