' Blob ID: f9f898d8340f3e5c006250d6b76a7c88d12f0bfd
' Original Path: /Fachliche_Beschreibung/plantuml/UserZahlungsdaten.puml
' Source: World of Code

@startuml

class UserZahlungsdaten {
    userid : int
    zahlungsdatenid : int
    status : Zahlungsdatenstatus
    zahlungsartID : Zahlungsart
    token : String
}

enum Zahlungsdatenstatus {
    akitv
    inaktiv
}

enum Zahlungsart {
    Paypal
    Kreditkarte
    Debitkarte
}

UserZahlungsdaten o-- User
UserZahlungsdaten o-- Zahlungsdaten
UserZahlungsdaten o-- Zahlungsdatenstatus
UserZahlungsdaten o-- Zahlungsart
@enduml
