' Blob ID: faf5601985762d381ccf19c6f95612bd700c3ed5
' Original Path: /Monitor/src/main/java/Model/Model.plantuml
' Source: World of Code

@startuml

title __MODEL's Class Diagram__\n


      class Model.Client {
          - address : String
          - community : String
          - snmp : Snmp
          + Client()
          + getCPU()
          + getMem()
          + getName()
          + getString()
          + stop()
          - getColumn()
          - getTarget()
          - start()
      }
  

      class Model.Log {
          - dataOutputStream : DataOutputStream
          - file : File
          + Log()
          + append()
          + close()
          + open()
      }
  

      class Model.Monitor {
          {static} - instance : Monitor
          - polling : int
          - running : boolean
          - threads : Map<String, Thread>
          + changePulling()
          {static} + getInstance()
          + getProcesses()
          + getUptime()
          + haveThreads()
          + join()
          + printText()
          + start()
          - Monitor()
      }
  

      class Model.Process {
          - centiseconds : float
          - cpu : float
          - mem : float
          - name : String
          - pid : Integer
          + Process()
          + getCentiseconds()
          + getPid()
          + setCentiseconds()
          + setCpu()
          + setMem()
          + toString()
      }
  

      class Model.VARIABLES {
          {static} ~ HRMEMORYSIZE : String
          {static} ~ HRSWRUNNAME : String
          {static} ~ HRSWRUNPERFCPU : String
          {static} ~ HRSWRUNPERFMEM : String
          {static} ~ HRSYSTEMUPTIME : String
      }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
