' Blob ID: fd79bce5793d9aadf2c418b4f0469699db52495e
' Original Path: /test6/顺序图/删除课程作业.puml
' Source: World of Code

@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title 删除课程作业顺序图

actor 老师
participant  API服务
participant  课程作业页面
database 数据库存储
老师-> 课程作业页面:点击删除课程作业
课程作业页面->课程作业页面:询问用户是否删除
课程作业页面->API服务:发送删除请求
API服务->数据库存储:服务请求删除对应的experiments_id ScoreItem_id的内容
数据库存储->数据库存储:将数据库中的对应内容删除
API服务-> 课程作业页面:返回响应信息到操作页面

@enduml
